dir:
  data_dir: data
  artifacts_dir: artifacts
  raw_dir: data/raw
  processed_dir: data/processed
  models_dir: models
  config_dir: configs
  mlruns_dir: mlruns
  transformers_dir: transformers

paths:
  raw_data_path: data/raw/Superstore.csv
  processed_data_path: data/processed/daily_data.csv
  transformer: models/transformer.pkl
  xgb_model_path: mlruns/278903003089258674/8c4b25cf29e8460ebd950c8240d3a977/artifacts/models/model.xgb
  quantile_encoder_path : transformers/quantile_transformer.pkl
  label_encoder_path : transformers/label_encoder.pkl
  scaler_encoder_path : transformers/scaler.pkl
